#!/usr/bin/env php
<?php

/**
 * @author  Baha2r
 * @license MIT
 * Date: 21/Oct/2019 23:27 PM
 *
 * Executes Guard commands
 **/

error_reporting(E_ALL & ~E_WARNING & ~E_NOTICE);

require __DIR__."/vendor/autoload.php";

use Symfony\Component\Console\Application;
use PHPGuard\Console\Commands;


$application = new Application("PHPGuard Library Console", "v2.0.0");

// ... register commands
$application->add(new Commands());
$application->run();