#!/usr/bin/env php
<?php

/**
 * @author  Baha2r
 * @license MIT
 * Date: 21/Oct/2019 23:27 PM
 *
 * Executes Guard commands
 **/

require __DIR__."/vendor/autoload.php";

use PHPGuard\Console\SetKeyCommand;
use PHPGuard\Console\DropKeyCommand;
use PHPGuard\Console\FreshCommand;
use PHPGuard\Console\TestSystemCommand;
use Symfony\Component\Console\Application;

$application = new Application("PHPGuard Console", "v3.1.6");

// ... register commands
$application->add(new SetKeyCommand());
$application->add(new DropKeyCommand());
$application->add(new FreshCommand());
$application->add(new TestSystemCommand());
$application->run();